use_frameworks!

platform :ios, '10.0'

target 'ZLInsetLabel_Example' do
  pod 'ZLInsetLabel', :path => '../'

  target 'ZLInsetLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
